type Package = {
  profile: string;
  email: string;
  contact: string;
  company: string;
  companyEmail: string; // New field for company email
  status: string;
  estimateValue: string;
  profileCreatedAt: string; // New field for profile creation date
};

export const packages: Package[] = [
  {
    profile: "John Doe",
    email: "john@example.com",
    contact: "+1 234-567-8900",
    company: "Travel Corp",
    companyEmail: "contact@travelcorp.com",
    status: "accepted",
    estimateValue: "$5,000",
    profileCreatedAt: "2023-12-05",
  },
  {
    profile: "Jane Smith",
    email: "jane@example.com",
    contact: "+1 234-567-8901",
    company: "Tech Solutions",
    companyEmail: "contact@techsolutions.com",
    status: "pending",
    estimateValue: "$10,000",
    profileCreatedAt: "2024-01-01",
  },
  {
    profile: "James Bond",
    email: "bond@example.com",
    contact: "+1 234-567-8902",
    company: "MI6",
    companyEmail: "hq@mi6.com",
    status: "declined",
    estimateValue: "$20,000",
    profileCreatedAt: "2023-11-15",
  },
  {
    profile: "Sarah Lee",
    email: "sarah@example.com",
    contact: "+1 234-567-8903",
    company: "Marketing Gurus",
    companyEmail: "info@marketinggurus.com",
    status: "accepted",
    estimateValue: "$15,000",
    profileCreatedAt: "2023-12-10",
  },
  {
    profile: "Michael Johnson",
    email: "michael@example.com",
    contact: "+1 234-567-8904",
    company: "Design Masters",
    companyEmail: "contact@designmasters.com",
    status: "pending",
    estimateValue: "$8,000",
    profileCreatedAt: "2024-02-05",
  },
  {
    profile: "Alice Cooper",
    email: "alice@example.com",
    contact: "+1 234-567-8905",
    company: "Green Innovations",
    companyEmail: "contact@greeninnovations.com",
    status: "accepted",
    estimateValue: "$12,000",
    profileCreatedAt: "2023-11-25",
  },
  {
    profile: "David Grant",
    email: "david@example.com",
    contact: "+1 234-567-8906",
    company: "Retail Ventures",
    companyEmail: "contact@retailventures.com",
    status: "declined",
    estimateValue: "$18,500",
    profileCreatedAt: "2023-12-20",
  },
  {
    profile: "Olivia Brown",
    email: "olivia@example.com",
    contact: "+1 234-567-8907",
    company: "Fintech Solutions",
    companyEmail: "support@fintechsolutions.com",
    status: "pending",
    estimateValue: "$22,000",
    profileCreatedAt: "2024-01-10",
  },
  {
    profile: "Ethan Clark",
    email: "ethan@example.com",
    contact: "+1 234-567-8908",
    company: "Smart Innovations",
    companyEmail: "contact@smartinnovations.com",
    status: "accepted",
    estimateValue: "$7,500",
    profileCreatedAt: "2023-11-30",
  },
  {
    profile: "Sophia Lee",
    email: "sophia@example.com",
    contact: "+1 234-567-8909",
    company: "Digital Dynamics",
    companyEmail: "info@digitaldynamics.com",
    status: "declined",
    estimateValue: "$25,000",
    profileCreatedAt: "2023-10-15",
  },
  {
    profile: "Christopher King",
    email: "christopher@example.com",
    contact: "+1 234-567-8910",
    company: "Media Productions",
    companyEmail: "contact@mediaproductions.com",
    status: "pending",
    estimateValue: "$30,000",
    profileCreatedAt: "2024-02-01",
  },
  {
    profile: "Isabella Martinez",
    email: "isabella@example.com",
    contact: "+1 234-567-8911",
    company: "Automotive Tech",
    companyEmail: "contact@automotivetech.com",
    status: "accepted",
    estimateValue: "$10,500",
    profileCreatedAt: "2023-12-18",
  },
  {
    profile: "Lucas Harris",
    email: "lucas@example.com",
    contact: "+1 234-567-8912",
    company: "Cloud Services",
    companyEmail: "support@cloudservices.com",
    status: "declined",
    estimateValue: "$9,000",
    profileCreatedAt: "2023-11-22",
  },
  {
    profile: "Charlotte Evans",
    email: "charlotte@example.com",
    contact: "+1 234-567-8913",
    company: "Logistics Solutions",
    companyEmail: "contact@logisticssolutions.com",
    status: "accepted",
    estimateValue: "$14,000",
    profileCreatedAt: "2023-12-12",
  },
  {
    profile: "Benjamin Walker",
    email: "benjamin@example.com",
    contact: "+1 234-567-8914",
    company: "Construction Co",
    companyEmail: "contact@constructionco.com",
    status: "pending",
    estimateValue: "$11,000",
    profileCreatedAt: "2024-01-15",
  },
  {
    profile: "Mia Wilson",
    email: "mia@example.com",
    contact: "+1 234-567-8915",
    company: "Healthcare Innovators",
    companyEmail: "contact@healthcareinnovators.com",
    status: "declined",
    estimateValue: "$16,000",
    profileCreatedAt: "2023-10-01",
  },
  {
    profile: "Daniel Moore",
    email: "daniel@example.com",
    contact: "+1 234-567-8916",
    company: "Legal Advisors",
    companyEmail: "info@legaladvisors.com",
    status: "accepted",
    estimateValue: "$12,500",
    profileCreatedAt: "2023-12-30",
  },
  {
    profile: "Amelia Adams",
    email: "amelia@example.com",
    contact: "+1 234-567-8917",
    company: "Cyber Security Experts",
    companyEmail: "contact@cybersecurityexperts.com",
    status: "pending",
    estimateValue: "$35,000",
    profileCreatedAt: "2024-01-20",
  },
  {
    profile: "Matthew Robinson",
    email: "matthew@example.com",
    contact: "+1 234-567-8918",
    company: "AI Innovators",
    companyEmail: "support@aiinnovators.com",
    status: "declined",
    estimateValue: "$40,000",
    profileCreatedAt: "2023-11-18",
  },
  {
    profile: "Evelyn Scott",
    email: "evelyn@example.com",
    contact: "+1 234-567-8919",
    company: "Space Tech",
    companyEmail: "contact@spacetech.com",
    status: "accepted",
    estimateValue: "$50,000",
    profileCreatedAt: "2023-12-08",
  },
  {
    profile: "Henry Parker",
    email: "henry@example.com",
    contact: "+1 234-567-8920",
    company: "Blockchain Ventures",
    companyEmail: "info@blockchainventures.com",
    status: "accepted",
    estimateValue: "$13,000",
    profileCreatedAt: "2024-01-25",
  },
  {
    profile: "Nina Green",
    email: "nina@example.com",
    contact: "+1 234-567-8921",
    company: "Eco Solutions",
    companyEmail: "contact@ecosolutions.com",
    status: "pending",
    estimateValue: "$19,500",
    profileCreatedAt: "2024-02-10",
  },
  {
    profile: "Owen Mitchell",
    email: "owen@example.com",
    contact: "+1 234-567-8922",
    company: "VR Innovations",
    companyEmail: "contact@vrinnovations.com",
    status: "accepted",
    estimateValue: "$17,000",
    profileCreatedAt: "2023-12-02",
  },
  {
    profile: "Zoe Roberts",
    email: "zoe@example.com",
    contact: "+1 234-567-8923",
    company: "Quantum Tech",
    companyEmail: "support@quantumtech.com",
    status: "declined",
    estimateValue: "$21,000",
    profileCreatedAt: "2023-11-12",
  },
  {
    profile: "Jake Turner",
    email: "jake@example.com",
    contact: "+1 234-567-8924",
    company: "Robotics Inc.",
    companyEmail: "info@roboticsinc.com",
    status: "pending",
    estimateValue: "$23,000",
    profileCreatedAt: "2024-01-28",
  },
  {
    profile: "Lily Scott",
    email: "lily@example.com",
    contact: "+1 234-567-8925",
    company: "Smart City Solutions",
    companyEmail: "contact@smartcitysolutions.com",
    status: "accepted",
    estimateValue: "$28,000",
    profileCreatedAt: "2023-12-03",
  },
];
