export type Package = {
  profile: string;
  email: string;
  contact: string;
  company: string;
  status: string;
  estimateValue: string;
};

export const packages: Package[] = [
  {
    profile: "John Doe",
    email: "john@example.com",
    contact: "+1 234-567-8900",
    company: "Travel Corp",
    status: "accepted",
    estimateValue: "$5,000",
  },
  {
    profile: "Jane Smith",
    email: "jane@example.com",
    contact: "+1 234-567-8901",
    company: "Vacation Ltd",
    status: "pending",
    estimateValue: "$3,500",
  },
  {
    profile: "Alice Green",
    email: "alice@example.com",
    contact: "+1 234-567-8902",
    company: "Explore Co",
    status: "accepted",
    estimateValue: "$4,200",
  },
  {
    profile: "Bob White",
    email: "bob@example.com",
    contact: "+1 234-567-8903",
    company: "Holiday Ventures",
    status: "declined",
    estimateValue: "$2,800",
  },
  {
    profile: "Charlie Black",
    email: "charlie@example.com",
    contact: "+1 234-567-8904",
    company: "Global Tours",
    status: "pending",
    estimateValue: "$6,100",
  },
  {
    profile: "Diana Blue",
    email: "diana@example.com",
    contact: "+1 234-567-8905",
    company: "Adventure Travel",
    status: "accepted",
    estimateValue: "$7,500",
  },
  {
    profile: "Evan Gray",
    email: "evan@example.com",
    contact: "+1 234-567-8906",
    company: "Journey Enterprises",
    status: "pending",
    estimateValue: "$4,800",
  },
  {
    profile: "Fiona Red",
    email: "fiona@example.com",
    contact: "+1 234-567-8907",
    company: "Wanderlust Travels",
    status: "accepted",
    estimateValue: "$5,400",
  },
  {
    profile: "George Purple",
    email: "george@example.com",
    contact: "+1 234-567-8908",
    company: "Holiday Horizons",
    status: "declined",
    estimateValue: "$3,000",
  },
  {
    profile: "Hannah White",
    email: "hannah@example.com",
    contact: "+1 234-567-8909",
    company: "Globetrotter Expeditions",
    status: "pending",
    estimateValue: "$6,600",
  },
  {
    profile: "Ivy Black",
    email: "ivy@example.com",
    contact: "+1 234-567-8910",
    company: "Pathfinder Adventures",
    status: "accepted",
    estimateValue: "$4,000",
  },
  {
    profile: "Jack Gray",
    email: "jack@example.com",
    contact: "+1 234-567-8911",
    company: "Pioneering Journeys",
    status: "pending",
    estimateValue: "$5,800",
  },
  {
    profile: "Kara Silver",
    email: "kara@example.com",
    contact: "+1 234-567-8912",
    company: "Voyage Global",
    status: "declined",
    estimateValue: "$2,200",
  },
  {
    profile: "Liam Green",
    email: "liam@example.com",
    contact: "+1 234-567-8913",
    company: "Summit Travels",
    status: "accepted",
    estimateValue: "$6,000",
  },
  {
    profile: "Mia Blue",
    email: "mia@example.com",
    contact: "+1 234-567-8914",
    company: "Adventure Seekers",
    status: "pending",
    estimateValue: "$7,100",
  },
  {
    profile: "Nina Yellow",
    email: "nina@example.com",
    contact: "+1 234-567-8915",
    company: "Elite Expeditions",
    status: "accepted",
    estimateValue: "$8,000",
  },
  {
    profile: "Oliver Pink",
    email: "oliver@example.com",
    contact: "+1 234-567-8916",
    company: "Tour Experts",
    status: "pending",
    estimateValue: "$5,200",
  },
  {
    profile: "Paul Orange",
    email: "paul@example.com",
    contact: "+1 234-567-8917",
    company: "Epic Adventures",
    status: "accepted",
    estimateValue: "$9,300",
  },
  {
    profile: "Quincy Brown",
    email: "quincy@example.com",
    contact: "+1 234-567-8918",
    company: "Wonder World Tours",
    status: "declined",
    estimateValue: "$4,500",
  },
  {
    profile: "Rachel Gray",
    email: "rachel@example.com",
    contact: "+1 234-567-8919",
    company: "Royal Travel Group",
    status: "pending",
    estimateValue: "$3,800",
  },
  {
    profile: "Sam White",
    email: "sam@example.com",
    contact: "+1 234-567-8920",
    company: "Global Pathfinders",
    status: "accepted",
    estimateValue: "$4,400",
  },
  {
    profile: "Tina Violet",
    email: "tina@example.com",
    contact: "+1 234-567-8921",
    company: "The Travel Agency",
    status: "pending",
    estimateValue: "$6,300",
  },
  {
    profile: "Ursula Blue",
    email: "ursula@example.com",
    contact: "+1 234-567-8922",
    company: "Ocean Breeze Travel",
    status: "declined",
    estimateValue: "$3,200",
  },
  {
    profile: "Victor Green",
    email: "victor@example.com",
    contact: "+1 234-567-8923",
    company: "Blue Horizon Adventures",
    status: "accepted",
    estimateValue: "$7,800",
  },
  {
    profile: "Wendy Black",
    email: "wendy@example.com",
    contact: "+1 234-567-8924",
    company: "Explorer's Paradise",
    status: "pending",
    estimateValue: "$5,600",
  },
  {
    profile: "Xander Red",
    email: "xander@example.com",
    contact: "+1 234-567-8925",
    company: "Journey Masters",
    status: "declined",
    estimateValue: "$4,000",
  },
  {
    profile: "Yasmine Yellow",
    email: "yasmine@example.com",
    contact: "+1 234-567-8926",
    company: "Global Exploration",
    status: "accepted",
    estimateValue: "$5,700",
  },
  {
    profile: "Zane Orange",
    email: "zane@example.com",
    contact: "+1 234-567-8927",
    company: "Wanderers World",
    status: "pending",
    estimateValue: "$6,500",
  },
  {
    profile: "John Doe",
    email: "john@example.com",
    contact: "+1 234-567-8900",
    company: "Travel Corp",
    status: "accepted",
    estimateValue: "$5,000",
  },
  {
    profile: "Jane Smith",
    email: "jane@example.com",
    contact: "+1 234-567-8901",
    company: "Vacation Ltd",
    status: "pending",
    estimateValue: "$3,500",
  },
  {
    profile: "Alice Green",
    email: "alice@example.com",
    contact: "+1 234-567-8902",
    company: "Explore Co",
    status: "accepted",
    estimateValue: "$4,200",
  },
  {
    profile: "Bob White",
    email: "bob@example.com",
    contact: "+1 234-567-8903",
    company: "Holiday Ventures",
    status: "declined",
    estimateValue: "$2,800",
  },
  {
    profile: "Charlie Black",
    email: "charlie@example.com",
    contact: "+1 234-567-8904",
    company: "Global Tours",
    status: "pending",
    estimateValue: "$6,100",
  },
  {
    profile: "Diana Blue",
    email: "diana@example.com",
    contact: "+1 234-567-8905",
    company: "Adventure Travel",
    status: "accepted",
    estimateValue: "$7,500",
  },
  {
    profile: "Evan Gray",
    email: "evan@example.com",
    contact: "+1 234-567-8906",
    company: "Journey Enterprises",
    status: "pending",
    estimateValue: "$4,800",
  },
  {
    profile: "Fiona Red",
    email: "fiona@example.com",
    contact: "+1 234-567-8907",
    company: "Wanderlust Travels",
    status: "accepted",
    estimateValue: "$5,400",
  },
  {
    profile: "George Purple",
    email: "george@example.com",
    contact: "+1 234-567-8908",
    company: "Holiday Horizons",
    status: "declined",
    estimateValue: "$3,000",
  },
  {
    profile: "Hannah White",
    email: "hannah@example.com",
    contact: "+1 234-567-8909",
    company: "Globetrotter Expeditions",
    status: "pending",
    estimateValue: "$6,600",
  },
  {
    profile: "Ivy Black",
    email: "ivy@example.com",
    contact: "+1 234-567-8910",
    company: "Pathfinder Adventures",
    status: "accepted",
    estimateValue: "$4,000",
  },
  {
    profile: "Jack Gray",
    email: "jack@example.com",
    contact: "+1 234-567-8911",
    company: "Pioneering Journeys",
    status: "pending",
    estimateValue: "$5,800",
  },
  {
    profile: "Kara Silver",
    email: "kara@example.com",
    contact: "+1 234-567-8912",
    company: "Voyage Global",
    status: "declined",
    estimateValue: "$2,200",
  },
  {
    profile: "Liam Green",
    email: "liam@example.com",
    contact: "+1 234-567-8913",
    company: "Summit Travels",
    status: "accepted",
    estimateValue: "$6,000",
  },
  {
    profile: "Mia Blue",
    email: "mia@example.com",
    contact: "+1 234-567-8914",
    company: "Adventure Seekers",
    status: "pending",
    estimateValue: "$7,100",
  },
  {
    profile: "Nina Yellow",
    email: "nina@example.com",
    contact: "+1 234-567-8915",
    company: "Elite Expeditions",
    status: "accepted",
    estimateValue: "$8,000",
  },
  {
    profile: "Oliver Pink",
    email: "oliver@example.com",
    contact: "+1 234-567-8916",
    company: "Tour Experts",
    status: "pending",
    estimateValue: "$5,200",
  },
  {
    profile: "Paul Orange",
    email: "paul@example.com",
    contact: "+1 234-567-8917",
    company: "Epic Adventures",
    status: "accepted",
    estimateValue: "$9,300",
  },
  {
    profile: "Quincy Brown",
    email: "quincy@example.com",
    contact: "+1 234-567-8918",
    company: "Wonder World Tours",
    status: "declined",
    estimateValue: "$4,500",
  },
  {
    profile: "Rachel Gray",
    email: "rachel@example.com",
    contact: "+1 234-567-8919",
    company: "Royal Travel Group",
    status: "pending",
    estimateValue: "$3,800",
  },
  {
    profile: "Sam White",
    email: "sam@example.com",
    contact: "+1 234-567-8920",
    company: "Global Pathfinders",
    status: "accepted",
    estimateValue: "$4,400",
  },
  {
    profile: "Tina Violet",
    email: "tina@example.com",
    contact: "+1 234-567-8921",
    company: "The Travel Agency",
    status: "pending",
    estimateValue: "$6,300",
  },
  {
    profile: "Ursula Blue",
    email: "ursula@example.com",
    contact: "+1 234-567-8922",
    company: "Ocean Breeze Travel",
    status: "declined",
    estimateValue: "$3,200",
  },
  {
    profile: "Victor Green",
    email: "victor@example.com",
    contact: "+1 234-567-8923",
    company: "Blue Horizon Adventures",
    status: "accepted",
    estimateValue: "$7,800",
  },
  {
    profile: "Wendy Black",
    email: "wendy@example.com",
    contact: "+1 234-567-8924",
    company: "Explorer's Paradise",
    status: "pending",
    estimateValue: "$5,600",
  },
  {
    profile: "Xander Red",
    email: "xander@example.com",
    contact: "+1 234-567-8925",
    company: "Journey Masters",
    status: "declined",
    estimateValue: "$4,000",
  },
  {
    profile: "Yasmine Yellow",
    email: "yasmine@example.com",
    contact: "+1 234-567-8926",
    company: "Global Exploration",
    status: "accepted",
    estimateValue: "$5,700",
  },
  {
    profile: "Zane Orange",
    email: "zane@example.com",
    contact: "+1 234-567-8927",
    company: "Wanderers World",
    status: "pending",
    estimateValue: "$6,500",
  },
];
